[package]
name = "cni"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fs2 = "0.4.3"
libc = "0.2.186"
proto = { path = "../proto" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.27.0"
tokio = { version = "1.52.0", features = ["macros", "net", "rt-multi-thread", "signal"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tonic = "0.14.6"
