syntax = "proto3";

package shared.v1;

import "shared/v1/container.proto";
import "shared/v1/resources.proto";

enum PodStatus {
  PENDING = 0;
  RUNNING = 1;
  SUCCEEDED = 2;
  FAILED = 3;
  UNKNOWN = 4;
  NO_NODE_AVAILABLE = 5;
}

// Basic Pod for scheduling
message Pod {
  string name = 1;
  PodStatus status = 2;
  Resources requests = 3;
  Resources limits = 4;
}

message PodSpec {
  string namespace = 1;
  repeated Container containers = 2;
}

message PodWithSpec {
  Pod pod = 1;
  PodSpec spec = 2;
}

// Full pod view: spec + runtime state
message PodDetail {
  PodWithSpec core = 1;
  repeated ContainerStatus container_statuses = 2;
  optional string pod_ip = 3;
  optional string message = 4;
  Resources resource_usage = 5;
  string node_name = 6;
  optional string unschedulable_reason = 7;
}
