[package]
name = "scheduler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4.6.6", features = ["derive", "env"] }
prost = "0.14.4"
proto = { path = "../proto" }
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = "0.1.18"
tonic = { version = "0.14.6", features = ["tls-ring"] }
tonic-prost = "0.14.6"

