[package]
name = "barectl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.6.6", features = ["derive", "env"] }
proto = { path = "../proto" }
tokio = { version = "1.53.1", features = ["full"] }
tonic = "0.14.6"
