[package]
name = "barectl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.6.6", features = ["derive", "env"] }
clap_complete = "4.6.9"
proto = { path = "../proto" }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2.0"
tokio = { version = "1.53.1", features = ["full"] }
tonic = "0.14.6"
