[package]
name = "proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
prost = "0.14.4"
serde = { version = "1.0.228", features = ["derive"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"
